# /d 指window10中的D盘
version: "3.7"
services:
    nginx1.17:
        image: nginx:1.17
        ports:
            - "80:80"
        volumes:
            - ./nginx1.17/nginx.conf:/etc/nginx/nginx.conf
            - /d/projects/php/study:/study
        depends_on:
            - php7.3
        environment: 
            - TZ=Asia/Shanghai
        privileged: true
    php7.3:
        build: ./php7.3
        image: php:7.3-fpm-cong
        volumes:
            - ./php7.3/php.ini:/usr/local/etc/php/php.ini
            - /d/projects/php/study:/study
        depends_on:
            - redis5.0
        cap_add: #对php-fpm慢日志有影响，https://blog.csdn.net/qq_30923243/article/details/101294985
            - SYS_PTRACE
        environment: 
            - TZ=Asia/Shanghai
        privileged: true
    redis5.0:
        image: redis:5.0
        volumes:
            - ./redis5.0/redis.conf:/usr/local/etc/redis/redis.conf
        environment: 
            - TZ=Asia/Shanghai
        privileged: true
        command: redis-server /usr/local/etc/redis/redis.conf
    mysql8.0:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - /d/data/mysql8.0_study:/var/lib/mysql
    mongo4.2:
        image: mongo:4.2
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
    rabbitmq3.7:
        image: rabbitmq:3.7
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./rabbitmq3.7:/etc/rabbitmq
        environment: 
            - TZ=Asia/Shanghai #无效，原因待分析
    golang1.13:
        image: golang:1.13
        volumes:
            - /d/projects/gopath:/go
        stdin_open: true #类似docker run -i
        tty: true #启动后，保持让容器不自动退出
        privileged: true #提供真实的root权限
        environment:
            - LANG=C.UTF-8 #容器支持中文
    openjdk:
        image: openjdk
        volumes:
            - /d/projects/java:/projects
        stdin_open: true
        tty: true
        privileged: true